name: "Anand Doshi"
highlighter: rouge
timezone: Asia/Kolkata
markdown: kramdown
description: "generalist; programmer, front-end developer, system administrator, finisher"
url: https://apd.is
permalink: none
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  - scope:
      path: "/blog/*"
    values:
      sitemap: false
  - scope:
      path: "/old/*"
    values:
      sitemap: false
  